version: '3.11'
services:
  web:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "9569:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./T-box:/T-box
      - ./odoo.conf:/etc/odoo/odoo.conf
    secrets:
      - postgresql_password
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  
volumes:
  odoo-web-data:
  odoo-db-data:

